# Generated by Django 4.0.6 on 2022-07-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_gametype_game_eventgamer_event_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Gamer',
        ),
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
            preserve_default=False,
        ),
    ]
